export const CHARACTERS = {
  thomas: {
    name: "THOMAS",
    color: "#3b82f6",
    darkColor: "#1d4ed8",
    glowColor: "rgba(59,130,246,0.6)",
    emoji: "🚂",
    description: "Lays tracks, summons train!",
    speed: 1.8,
    hp: 200, // BUFF: 150 → 200
    ability: "train",
    abilityDamage: 10, // NERF: 12 → 10
    abilityColor: '#3b82f6',
    abilityCooldown: 9000,
    ultimateName: "GHOST TRAIN",
    ultimateColor: "#3b82f6",
    ultimateEffect: "Charge → 10 ghost trains storm (30 dmg each)",
    ultimateCost: 4,
  },
  anchor: {
    name: "ANCHOR",
    color: "#9ca3af",
    darkColor: "#4b5563",
    glowColor: "rgba(156,163,175,0.6)",
    emoji: "⚓",
    description: "Chain hook pulls enemies",
    speed: 1.5,
    hp: 200, // BUFF: 150 → 200
    ability: "hook",
    abilityDamage: 6, // NERF: 8 → 6
    abilityColor: '#9ca3af',
    abilityCooldown: 7000,
    ultimateName: "DEAD ANCHOR",
    ultimateColor: "#9ca3af",
    ultimateEffect: "Chain bind + escalating ram, knockback release",
    ultimateCost: 4,
  },
  blaze: {
    name: "BLAZE",
    color: "#ef4444",
    darkColor: "#991b1b",
    glowColor: "rgba(239,68,68,0.6)",
    emoji: "🔥",
    description: "Shoots fireballs!",
    speed: 2.0,
    hp: 200, // BUFF: 150 → 200
    ability: "fireball",
    abilityDamage: 6, // NERF: 8 → 6
    abilityColor: '#ef4444',
    abilityCooldown: 2500,
    ultimateName: "INFERNO",
    ultimateColor: "#ef4444",
    ultimateEffect: "2.5s charge → 8s inferno mode, rapid fire-arrow barrage",
    ultimateCost: 5,
  },
  volt: {
    name: "VOLT",
    color: "#a78bfa",
    darkColor: "#6d28d9",
    glowColor: "rgba(167,139,250,0.6)",
    emoji: "⚡",
    description: "Fast + high collision dmg",
    speed: 2.5,
    hp: 200, // BUFF: 150 → 200
    ability: "dash",
    abilityDamage: 8, // NERF: 12 → 8 (collision dmg too high)
    abilityColor: '#a78bfa',
    abilityCooldown: 2500,
    ultimateName: "THUNDER GOD",
    ultimateColor: "#a78bfa",
    ultimateEffect: "Charge → 8x light-speed dash + static field, then 8s electric-trail mode",
    ultimateCost: 4,
  },
  phantom: {
    name: "PHANTOM",
    color: "#06b6d4",
    darkColor: "#0e7490",
    glowColor: "rgba(6,182,212,0.6)",
    emoji: "👻",
    description: "Teleports behind enemy",
    speed: 2.3,
    hp: 200, // BUFF: 150 → 200
    ability: "teleport",
    abilityDamage: 5, // NERF: 7 → 5
    abilityColor: '#06b6d4',
    abilityCooldown: 2500,
    ultimateName: "PHANTOM ARMY",
    ultimateColor: "#06b6d4",
    ultimateEffect: "Splits into 5 identical clones for 10s",
    ultimateCost: 4,
  },
  titan: {
    name: "TITAN",
    color: "#f97316",
    darkColor: "#c2410c",
    glowColor: "rgba(249,115,22,0.6)",
    emoji: "🪨",
    description: "Shockwave knocks back",
    speed: 1.4,
    hp: 220, // BUFF: 150 → 220 (tankiest)
    ability: "slam",
    abilityDamage: 8, // NERF: 10 → 8
    abilityColor: '#f97316',
    abilityCooldown: 4500,
    ultimateName: "IRON EARTH",
    ultimateColor: "#f97316",
    ultimateEffect: "Slam + stacking armor DR (Hardened passive)",
    ultimateCost: 4,
  },
  wizard: {
    name: "WIZARD",
    color: "#8b5cf6",
    darkColor: "#6d28d9",
    glowColor: "rgba(139,92,246,0.6)",
    emoji: "🧙",
    description: "Freezes enemy in place!",
    speed: 1.6,
    hp: 200, // BUFF: 150 → 200
    ability: "freeze",
    abilityDamage: 6, // NERF: 8 → 6
    abilityColor: '#a5f3fc',
    abilityCooldown: 5000,
    ultimateName: "CELESTIAL JUDGMENT",
    ultimateColor: "#8b5cf6",
    ultimateEffect: "Eye of cosmos: beam tracking → 7 meteors → 8s curse-freeze mode",
    ultimateCost: 5,
  },
  robot: {
    name: "ROBOT",
    color: "#64748b",
    darkColor: "#334155",
    glowColor: "rgba(100,116,139,0.6)",
    emoji: "🤖",
    description: "Short-range laser",
    speed: 1.5,
    hp: 200, // BUFF: 150 → 200
    ability: "laser",
    abilityDamage: 10, // NERF: 15 → 10
    abilityColor: '#ef4444',
    abilityCooldown: 4500,
    ultimateName: "ARTILLERY GRID",
    ultimateColor: "#64748b",
    ultimateEffect: "9-beam grid barrage + lock-on, then shrinking 2x2 mode",
    ultimateCost: 6,
  },
  bat: {
    name: "BAT",
    color: "#dc2626",
    darkColor: "#991b1b",
    glowColor: "rgba(220,38,38,0.6)",
    emoji: "🦇",
    description: "Life steal dash",
    speed: 2.7,
    hp: 200, // BUFF: 150 → 200
    ability: "lifesteal",
    abilityDamage: 6, // NERF: 9 → 6
    abilityColor: '#dc2626',
    abilityCooldown: 2500,
    ultimateName: "CRIMSON FEAST",
    ultimateColor: "#dc2626",
    ultimateEffect: "Lunge + 2s bite (25 dmg/s & heal), recoil 30 AOE",
    ultimateCost: 5,
  },
  // NEW CHARACTERS
  dragon: {
    name: "DRAGON",
    color: "#f59e0b",
    darkColor: "#b45309",
    glowColor: "rgba(245,158,11,0.6)",
    emoji: "🐉",
    description: "Breathes fire cone!",
    speed: 1.7,
    hp: 200, // BUFF: 150 → 200
    ability: "firebreath",
    abilityDamage: 8, // NERF: 12 → 8
    abilityColor: '#f59e0b',
    abilityCooldown: 3500,
    ultimateName: "DRAGON'S WRATH",
    ultimateColor: "#f59e0b",
    ultimateEffect: "5s charge → 3s locked fire laser (35/s) + burn trail",
    ultimateCost: 5,
  },
  ninja: {
    name: "NINJA",
    color: "#9CA3AF", // Stasis gray/silver
    darkColor: "#6B7280",
    glowColor: "rgba(165,243,252,0.55)", // crystalline blue tint
    emoji: "🥷",
    description: "Throws gray-steel kunai (slows on hit)!",
    speed: 2.4,
    hp: 200, // BUFF: 150 → 200
    ability: "kunai",
    abilityDamage: 4,
    abilityColor: '#9CA3AF',
    abilityCooldown: 2500, // 2.5s
    ultimateName: "TIME DILATION",
    ultimateColor: "#9CA3AF",
    ultimateEffect: "Freezes ALL enemies & projectiles for 2s — ninja moves & spams 12 kunai that all fly on resume",
    ultimateCost: 6,
  },
  bomber: {
    name: "BOMBER",
    color: "#84cc16",
    darkColor: "#4d7c0f",
    glowColor: "rgba(132,204,22,0.6)",
    emoji: "💣",
    description: "Drops explosive bomb",
    speed: 1.6,
    hp: 200, // BUFF: 150 → 200
    ability: "bomb",
    abilityDamage: 12, // NERF: 16 → 12
    abilityColor: '#84cc16',
    abilityCooldown: 6500,
    ultimateName: "CARPET BOMBING",
    ultimateColor: "#84cc16",
    ultimateEffect: "5 sweeping bomb waves → full-arena blast + landing",
    ultimateCost: 7,
  },
  phoenix: {
    name: "PHOENIX",
    color: "#f43f5e",
    darkColor: "#e11d48",
    glowColor: "rgba(244,63,94,0.6)",
    emoji: "🦅",
    description: "Fire aura + revive once",
    speed: 2.1,
    hp: 200, // BUFF: 150 → 200
    ability: "fireaura",
    abilityDamage: 6, // NERF: 8 → 6
    abilityColor: '#f43f5e',
    abilityCooldown: 2000,
    ultimateName: "RISING SUN",
    ultimateColor: "#f43f5e",
    ultimateEffect: "Sun rains 8 fireballs → reborn shockwave → 8s aura mode",
    ultimateCost: 5,
  },
  king: {
    name: "KING",
    color: "#fbbf24",
    darkColor: "#b45309",
    glowColor: "rgba(251,191,36,0.6)",
    emoji: "👑",
    description: "Crown stun + 18 dmg",
    speed: 1.5,
    hp: 200, // BUFF: 150 → 200
    ability: "crown",
    abilityDamage: 8, // NERF: 12 → 8
    abilityColor: '#fbbf24',
    abilityCooldown: 5500,
    ultimateName: "ROYAL DECREE",
    ultimateColor: "#fbbf24",
    ultimateEffect: "8s immune mode, 24 tracking golden swords (10 each)",
    ultimateCost: 7,
  },
  glacier: {
    name: "GLACIER",
    color: "#7dd3fc",
    darkColor: "#0369a1",
    glowColor: "rgba(125,211,252,0.6)",
    emoji: "❄️",
    description: "Frostbite slow + Absolute Zero",
    speed: 3.0,
    hp: 200,
    ability: "frostbite",
    abilityDamage: 7,
    abilityColor: '#7dd3fc',
    abilityCooldown: 1400,
    ultimateName: "ABSOLUTE ZERO",
    ultimateColor: "#7dd3fc",
    ultimateEffect: "Blizzard storm then 8s permafrost: enemy slowed, hits freeze",
    ultimateCost: 6,
  },
  venom: {
    name: "VENOM",
    color: "#a3e635",
    darkColor: "#4d7c0f",
    glowColor: "rgba(163,230,53,0.6)",
    emoji: "☠️",
    description: "Toxic DoT poison + Pandemic",
    speed: 3.4,
    hp: 190,
    ability: "poison",
    abilityDamage: 4,
    abilityColor: '#a3e635',
    abilityCooldown: 1500,
    ultimateName: "PANDEMIC",
    ultimateColor: "#84cc16",
    ultimateEffect: "Toxic outbreak then 8s plague: doubled poison, life drain",
    ultimateCost: 6,
  },
  seraph: {
    name: "SERAPH",
    color: "#fde68a",
    darkColor: "#d97706",
    glowColor: "rgba(253,230,138,0.6)",
    emoji: "✨",
    description: "Heal-over-time + shield, Sanctuary",
    speed: 3.2,
    hp: 210,
    ability: "mend",
    abilityDamage: 3,
    abilityColor: '#fcd34d',
    abilityCooldown: 1600,
    ultimateName: "SANCTUARY",
    ultimateColor: "#fde68a",
    ultimateEffect: "Holy nova then 8s sanctuary: strong regen + 55% DR + retaliation",
    ultimateCost: 6,
  },
}

export const CHAR_KEYS = Object.keys(CHARACTERS)
